Fix ImportError: 'get_current_traceback' from 'werkzeug.debug.tbtools'
Fix for ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' conflict with dash for studio

celery-beat      |     from .dash_demo import app
celery-beat      |   File "/app/monitor/dash_demo.py", line 8, in <module>
celery-beat      |     import dash
celery-beat      |   File "/usr/local/lib/python3.8/site-packages/dash/__init__.py", line 5, in <module>
celery-beat      |     from .dash import Dash, no_update  # noqa: F401,E402
celery-beat      |   File "/usr/local/lib/python3.8/site-packages/dash/dash.py", line 22, in <module>
celery-beat      |     from werkzeug.debug.tbtools import get_current_traceback
celery-beat      | ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/usr/local/lib/python3.8/site-packages/werkzeug/debug/tbtools.py)

Reproduce the error:
1- Install stackn (docker-compose up)

Ref: plotly/dash#1993